name: Create EXE

on:
  push:
    branches:
      - main  # Adjust to your branch name

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner with Node.js 16

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0  # Specify the Python version you need
          architecture: x64  # Use x64 or x86 based on your requirements

      - name: Install Dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt
        working-directory: ./  # Modify this path

      - name: Create .env File
        run: echo 'API_KEY=${{secrets.API_KEY}}' > .env

      - name: Create Version File
        run: python -c "import datetime; print(datetime.datetime.now().strftime('%Y-%m-%dT%H:%M:%SZ'))" > version.txt
        
      - name: Build EXE
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon "icon.ico" --name "NotaireCiclade" --add-data "icon.ico;." --add-data ".env;." --add-data "updater.exe;." --add-data "version.txt;." --add-data "CapSolver;CapSolver/" --distpath ./output "notaire_ciclade.py"

        working-directory: ./  # Modify this path
      - name: Copy EXE to GitHub workspace
        run: |
          git config --global user.email "chandanhans2003@gmail.com"
          git config --global user.name "ChandanHans"
          git add -f ./output/NotaireCiclade.exe
          git commit -m "NotaireCiclade.exe"
          git push
